/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#111318",
        error: "#ffb4ab",
        secondary: "#d8b9ff",
        "outline-variant": "#3b494b",
        "tertiary-fixed": "#e2e2e2",
        "inverse-primary": "#006970",
        "surface-variant": "#333539",
        "on-primary-fixed": "#002022",
        "primary-container": "#00f0ff",
        "inverse-on-surface": "#2f3035",
        "surface-container-highest": "#333539",
        "inverse-surface": "#e2e2e8",
        "surface-tint": "#00dbe9",
        "on-primary": "#00363a",
        "surface-container-lowest": "#0c0e12",
        "secondary-fixed-dim": "#d8b9ff",
        "on-surface": "#e2e2e8",
        "secondary-fixed": "#eddcff",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container": "#1e2024",
        primary: "#dbfcff",
        "on-primary-container": "#006970",
        "on-secondary-fixed": "#290055",
        "primary-fixed": "#7df4ff",
        "on-error": "#690005",
        "primary-fixed-dim": "#00dbe9",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-dim": "#111318",
        "surface-container-high": "#282a2e",
        "secondary-container": "#6e06d0",
        "on-secondary": "#450086",
        "surface-bright": "#37393e",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-low": "#1a1c20",
        "on-surface-variant": "#b9cacb",
        "tertiary-container": "#d9d9d9",
        background: "#111318",
        "on-error-container": "#ffdad6",
        outline: "#849495",
        "on-secondary-fixed-variant": "#6200bc",
        tertiary: "#f5f5f5",
        "on-secondary-container": "#d5b5ff",
        "on-tertiary": "#2f3131",
        "error-container": "#93000a",
        "on-tertiary-container": "#5d5f5f",
        "on-background": "#e2e2e8",
        "on-primary-fixed-variant": "#004f54",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
